//https://canvas.instructure.com/doc/api/courses.html
export interface CanvasCourses {
  id: string,
  sis_course_id: string | null,
  uuid: string,
  integration_id: string | null,
  sis_import_id: string,
  name: string,
  course_code: string,
  workflow_state: string,
  account_id: string,
  root_account_id: string,
  enrollment_term_id: string,
  grading_standard_id: string,
  grade_passback_setting: string,
  created_at: Date | string,
  start_at: Date | string,
  end_at: Date | string,
  locale: string,
  enrollments: string | null,
  total_students: number | string,
  calendar: string | null,
  default_view: string,
  syllabus_body: string,
  needs_grading_count: number | string,
  term: null,
  course_progress: null,
  apply_assignment_group_weights: boolean,
  permissions: {create_discussion_topic: boolean, create_announcement: boolean},
  is_public: boolean,
  is_public_to_auth_users: boolean,
  public_syllabus: boolean,
  public_syllabus_to_auth: boolean,
  public_description: string,
  storage_quota_mb: number | string,
  storage_quota_used_mb: number | string,
  hide_final_grades: boolean,
  license: string,
  allow_student_assignment_edits: boolean,
  allow_wiki_comments: boolean,
  allow_student_forum_attachments: boolean,
  open_enrollment: boolean,
  self_enrollment: boolean,
  restrict_enrollments_to_course_dates: boolean,
  course_format: string,
  access_restricted_by_date: boolean,
  time_zone: string,
  blueprint: boolean,
  blueprint_restrictions: {content: boolean, points: boolean, due_dates: boolean, availability_dates: boolean},
  blueprint_restrictions_by_object_type: {assignment:{content: boolean, points: boolean}, wiki_page:{content: boolean}}
}
